# Generated by Django 3.1.3 on 2020-11-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('subject_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('prerequsite', models.CharField(max_length=512)),
                ('introduction', models.CharField(max_length=512)),
                ('average_workload', models.IntegerField()),
                ('average_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GenedSatisfaction',
            fields=[
                ('subject_number_type', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralEducation',
            fields=[
                ('type', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('a_plus', models.IntegerField()),
                ('a', models.IntegerField()),
                ('a_minus', models.IntegerField()),
                ('b_plus', models.IntegerField()),
                ('b', models.IntegerField()),
                ('b_minus', models.IntegerField()),
                ('c_plus', models.IntegerField()),
                ('c', models.IntegerField()),
                ('c_minus', models.IntegerField()),
                ('d_plus', models.IntegerField()),
                ('d', models.IntegerField()),
                ('d_minus', models.IntegerField()),
                ('w', models.IntegerField()),
                ('f', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('year_term', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=64)),
                ('term', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, year_term=''), name='semester_year_term_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, year=''), name='semester_year_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, term=''), name='semester_term_not_null_constraint'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='year_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester'),
        ),
        migrations.AddConstraint(
            model_name='generaleducation',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, type=''), name='general_education_not_null_constraint'),
        ),
        migrations.AddField(
            model_name='genedsatisfaction',
            name='subject_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='genedsatisfaction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.generaleducation'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(average_workload__gte='0'), name='course_averge_workload_gte_zero_constraint'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(average_rating__gte='0'), name='course_averge_rating_gte_zero_constraint'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, subject_number=''), name='course_subject_number_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, subject=''), name='course_subject_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, number=''), name='course_number_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, title=''), name='course_title_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('subject', 'number'), name='course_title_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, first_name=''), name='grade_first_name_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, last_name=''), name='grade_last_name_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='genedsatisfaction',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, subject_number_type=''), name='gened_satisfication_subject_number_type_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='genedsatisfaction',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, subject_number=''), name='gened_satisfication_subject_numbe_not_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='genedsatisfaction',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, type=''), name='gened_satisfication_type_not_null_constraint'),
        ),
    ]
