# Generated by Django 3.1.3 on 2020-11-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='course_averge_workload_gte_zero_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='course_averge_rating_gte_zero_constraint',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(average_workload__gte='-1'), name='course_averge_workload_gte_zero_constraint'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(average_rating__gte='-1'), name='course_averge_rating_gte_zero_constraint'),
        ),
    ]
