# Generated by Django 3.1.3 on 2020-11-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201120_0227'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='semester',
            table='Semester',
        ),
    ]
